name: Print Name
on:
  push:
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v4
      - name: Print name
        run: echo "Hello There, I am Raghav"
      - name: Install Dependencies
        run: npm ci
      - name: Print name
        run: npm test